article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name = 'article_list'),
    path('article-detail/<int:id>/', views.article_detail, name = 'article_detail'),
    path('article-create/', views.article_create, name = 'article_create'),
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
path('post-comment/<int:article_id>/', views.post_comment, name = 'post_comment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace = 'article')),
    path('userprofile/', include('userprofile.urls', namespace = 'userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace = 'comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('register/', views.user_register, name = 'register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
from django.urls import reverse

# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    # 内部类 class Meta 用于给 model 定义元数据

    total_views = models.PositiveIntegerField(default = 0)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body')

article/views.py
from .models import ArticlePost
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ArticlePostForm
from django.contrib.auth.models import User
import markdown
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from comment.models import Comment

def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    if search:
        if order == 'total_views':
            article_list = ArticlePost.objects.filter(
            Q(title__icontains = search)|
            Q(body__icontains = search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
            Q(title__icontains = search)|
            Q(body__icontains = search)
            )
    else:
        seach = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()

    paginator = Paginator(article_list, 6)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    context = {'articles':articles, 'order': order, 'search': search}

    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id = id)
    comments = Comment.objects.filter(article = id)
    article.total_views += 1
    article.save(update_fields = ['total_views'])
    md = markdown.Markdown(
    extensions = [
    'markdown.extensions.extra',
    'markdown.extensions.codehilite',
    # directory
    'markdown.extensions.toc',
    ])

    article.body = md.convert(article.body)
    context = {'article': article, 'toc': md.toc, 'comments': comments}
    return render(request, 'article/detail.html', context)

def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data = request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit = False)
            if not request.user.id:
                return HttpResponse("please log in first")
            new_article.author = User.objects.get(id = request.user.id)
            new_article.save()
            return redirect("article:article_list")
        else:
            return HttpResponse("illegal post request, please write again")
    else:
        article_post_form = ArticlePostForm()
        context = {'article_post_form':article_post_form}
        return render(request, 'article/create.html', context)

@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id = id)
        if request.user != article.author:
            return HttpResponse("You are not authorized to edit this article")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("only post request allowed")

@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id = id)
    if request.user != article.author:
        return HttpResponse("You are not authorized to edit this article")
    if request.method == "POST":
        article_post_form = ArticlePostForm(data = request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect("article:article_detail",id = id)
        else:
            return HttpResponse("illegal post request, please write again")
    # if GET
    else:
        article_post_form = ArticlePostForm()
        context = {'article':article, 'article_post_form': article_post_form}
        return render(request, 'article/update.html', context)

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} write article {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">title</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">body</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">complete</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    Article Detail
{% endblock title %}

{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">

      <div class = "col-9">
        <!-- 标题及作者 -->
        <h1 class="mt-4 mb-4">{{ article.title }}</h1>
        <div class="alert alert-success">
          <div>
            Author：{{ article.author }}
            {% if user == article.author %}
                <a href="#" onclick="confirm_delete()"> Delete </a>
                <a href="{% url "article:article_update" article.id %}">Edit</a>
            {% endif %}
          </div>
          <div>
            views: {{article.total_views}}
          </div>
            <form
              style="display:none;"
              id="safe_delete"
              action="{% url 'article:article_safe_delete' article.id %}"
              method="POST"
              >
              {% csrf_token %}
              <button type="submit">send</button>
            </form>
        </div>
      </div>
      <!-- directory -->
      <div class="col-3 mt-4">
          <h4><strong>directory</strong></h4>
          <hr>
          <div>
              {{ toc|safe }}
          </div>
        </div>
      </div>
        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>

        <!-- 发表评论 -->
        <hr>
        {% if user.is_authenticated %}
            <div>
                <form
                    action="{% url 'comment:post_comment' article.id %}"
                    method="POST"
                >
                {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                leave your comment here
                            </strong>
                        </label>
                        <textarea
                            type="text"
                            class="form-control"
                            id="body"
                            name="body"
                            rows="2"></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary ">submit</button>
                </form>
            </div>
            <br>
        {% else %}
            <br>
            <h5 class="row justify-content-center">
                please <a href="{% url 'userprofile:login' %}">&nbsp;log in&nbsp;</a> to reply
            </h5>
            <br>
        {% endif %}


        <!-- 显示评论 -->
        <h4>{{ comments.count }} total comments</h4>
        <div>
            {% for comment in comments %}
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong> at
                    <span style="color: green">
                        {{ comment.created|date:"Y-m-d H:i:s" }}
                    </span> said：
                </p>
                <pre style="font-family: inherit; font-size: 1em;">{{comment.body}}</pre>
            {% endfor %}
        </div>
</div>






<script>
  function confirm_delete(){
    layer.open(
    {
      title: "confirm deletion",
      content: "Do you want to delete this post?",
      yes: function(index, layero){
        $('form#safe_delete button').click();
        layer.close(index);
      },
    })
  }
</script>

{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    FrontPage
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label = "breadcrumb">
      <ol class = "breadcrumb">
        <li class = "breadcrumb-item">
          <a href = "{% url 'article:article_list' %}?search={{search}}">
            latest
          </a>
        </li>
        <li class = "breadcrumb-item">
          <a href = "{% url 'article:article_list' %}?order=total_views&search={{search}}">
            hottest
          </a>
        </li>
      </ol>
    <nav>

      <!-- 新增，搜索栏 -->
      <div class="row">
          <div class="col-auto mr-auto">
              <form class="form-inline" >
                  <label class="sr-only">content</label>
                  <input type="text"
                      class="form-control mb-2 mr-sm-2"
                      name="search"
                      placeholder="Search"
                      required
                  >
              </form>
          </div>
      </div>

      <!-- 新增，搜索提示语 -->
      {% if search %}
          {% if articles %}
              <h4><span style="color: red">"{{ search }}"</span>Searching Results：</h4>
              <hr>
          {% else %}
              <h4>There is not articles about <span style="color: red">"{{ search }}"</span></h4>
              <hr>
          {% endif %}
      {% endif %}


    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">Read</a>
                    <span>
                      <small class = "col align-self-end" style = "color: gray;">
                        views:{{article.total_views}}
                      </small>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>

    <!--page navigation-->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1 & order = {{order}}&search={{search}}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                       class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"class="btn btn-success">
                       class="btn btn-success"
                    >
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/update.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} edit article {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">title</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">body</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">complete</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}